name: Build Document
on: [push, pull_request, workflow_dispatch]
jobs:
    build_document:
        name: Build Document
        runs-on: ubuntu-20.04
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Build
                run: |
                    sudo apt update &&
                    sudo apt install -y asciidoctor ruby-asciidoctor-pdf pandoc &&
                    for file in docs/*.adoc; do
                        base=$(basename "$file" .adoc)
                        asciidoctor-pdf "$file" -o "docs/$base.pdf" &&
                        asciidoctor --backend docbook --out-file - "$file" | pandoc --from docbook --to docx --output "docs/$base.docx" &&
                        asciidoctor "$file" -o "docs/$base.html"
                    done
            -   uses: actions/upload-artifact@v3
                with:
                    path: |
                        docs/*.pdf
                        docs/*.docx
                        docs/*.html
                    if-no-files-found: 'error'
                       
    build_diff:
        name: Build Diff
        if: github.ref_name != 'main'
        needs:
            - build_document
        runs-on: ubuntu-20.04
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    ref: main
                    path: cps
            -   name: Checkout diff software
                uses: actions/checkout@v3
                with: 
                    repository: ahus1/asciidoc-diff
                    ref: f085aa908c963f74472d13bafc2f0fb1054801fe
                    path: diff
            -   name: Setup diff
                run: |
                    sudo apt update &&
                    sudo apt install -y asciidoctor npm &&
                    /bin/bash -c "cd diff && npm install"
            -   name: Get branch HTML doc
                uses: actions/download-artifact@v3
                with:
                    name: artifact
                    path: artifact
            -   name: Build main and create diff
                run: |
                    for file in cps/docs/*.adoc; do
                        base=$(basename "$file" .adoc)
                        echo $base
                        asciidoctor "$file" -o diff/bv2-cr1.html
                        mv "artifact/$base.html" diff/bv2-cr3.html &&
                        /bin/bash -c "cd diff && npm run diff" &&
                        mv diff/bv2-diff.html "diff_$base.html"
                        rm -rf diff/*.html
                    done
            -   name: Upload diff
                uses: actions/upload-artifact@v3
                with:
                    path:
                        diff_*.html
                    if-no-files-found: 'error'

